# Generated by Django 3.1.2 on 2021-03-05 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210305_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 19, 23, 19, 753730)),
        ),
    ]
