# Generated by Django 3.1.2 on 2021-03-05 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210306_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 24, 10, 825682)),
        ),
        migrations.AlterField(
            model_name='profileupdate',
            name='image',
            field=models.ImageField(default='image/pro_avter.png', null=True, upload_to='static/profile/'),
        ),
    ]
