# Generated by Django 3.1.2 on 2021-03-05 20:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20210306_0224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUpdate',
            new_name='ProfilUpdate',
        ),
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 40, 16, 238938)),
        ),
    ]
