# Generated by Django 3.1.2 on 2021-03-06 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210306_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 40, 3, 535455)),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='bio',
            field=models.TextField(default="Write Your 'Boi'"),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='image',
            field=models.ImageField(default='static/image/pro_avter.png', upload_to='profile/'),
        ),
    ]
