# Generated by Django 3.1.2 on 2021-03-06 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210306_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 42, 28, 945184)),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='image',
            field=models.ImageField(default='image/pro_avter.png', upload_to='profile/'),
        ),
    ]
