# Generated by Django 3.1.2 on 2021-03-13 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210313_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 25, 24, 908822)),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='image',
            field=models.ImageField(default='image/pro_avter.png', upload_to='static/profile/'),
        ),
    ]
