# Generated by Django 3.1.2 on 2021-03-13 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210313_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 31, 39, 939481)),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='image',
            field=models.ImageField(default='static/propic/pro_avter.png', upload_to='static/profile/'),
        ),
    ]
