# Generated by Django 3.1.7 on 2021-03-17 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210316_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 23, 28, 35, 316673)),
        ),
    ]
