# Generated by Django 3.1.7 on 2021-03-17 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210317_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 23, 35, 28, 918271)),
        ),
    ]
